apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx
  namespace: awx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awx
  template:
    metadata:
      labels:
        app: awx
    spec:
      tolerations:
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "fargate"
          effect: "NoSchedule"
      containers:
        - name: awx
          image: quay.io/ansible/awx:19.3.0
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            - name: DATABASE_HOST
              value: awx-postgres.awx.svc.cluster.local
            - name: DATABASE_NAME
              value: awx
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-config
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: awx-postgres-config
                  key: password
            - name: REDIS_HOST
              value: awx-redis-master.awx.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
