apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-projects
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-090dc94999ff063b8
    fsType: ext4
