apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
type: Opaque
stringData:
  admin_password: somepassword

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-config
  namespace: awx
type: Opaque
stringData:
  username: admin
  password: somepassword
